##This program detects if an email/message is spam (1) or not (0)
###Import Libraries

In [ ]:
#import libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

###Load the data

In [ ]:
#Load the data
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails (1).csv


###Read the CSV file

In [ ]:
#Read the CSV file
df = pd.read_csv('emails.csv')

##Print the first five rows of data

In [ ]:
#Print first five rows of dataset
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

###Print the shape of the dataset(Get the number of rows and columns)

In [ ]:
#Print the number of rows and columns
df.shape

(5728, 2)

###Get the column names

In [ ]:
#Print the column names
df.columns

Index(['text', 'spam'], dtype='object')

###Check for duplicates and remove them

In [ ]:
#Remove duplicates if any
df.drop_duplicates(inplace = True)

###Show the new shape (number of rows and columns)

In [ ]:
#Show the new shape
df.shape

(5695, 2)

###Show the number of missing data (if any) for each column

In [ ]:
#Show the number of missing data
df.isnull().sum()

text    0
spam    0
dtype: int64

###Download the stopwords package

In [ ]:
#Download the stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

#Processing the input for a cleaner Text

In [ ]:
#Process Text
def process_text(text):
  #1 Remove punctuation
  #2 Remove Stopwords
  #3 Return a list of clean text words

  #1 
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)

  #2
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  #3
  return clean_words

In [ ]:
#Show the tokenisation(a list of tokens also called lemmas)
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

###Convert a collection of text to a matrix of tokens

In [ ]:
#Convert a collection of text to a matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer = process_text).fit_transform(df['text'])


##Split the data into 80% training and 20% testing

In [ ]:
#Split the data into 80% training data and 20 % testing data
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test  = train_test_split(messages_bow , df['spam'], test_size =0.2,random_state =0)

##Training the model

In [ ]:
#Create and train Naive-Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train,y_train)

##Printing the predicitons

In [ ]:
#Print the predictions
print(classifier.predict(X_train))

#Print the actual values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


##Evaluate model on the training data set

In [ ]:
#Evaluate model on training dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred= classifier.predict(X_train)
print(classification_report(y_train,pred))
print()
print('Confusion Matrix:\n', confusion_matrix(y_train,pred))
print()
print('Accuracy : ', accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix:
 [[3445   12]
 [   1 1098]]

Accuracy :  0.9971466198419666


##Evaluating model on testing dataset

In [ ]:
#Print the predictions
print(classifier.predict(X_test))

#Print the actual values
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [ ]:
#Evaluate model on testing dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred= classifier.predict(X_test)
print(classification_report(y_test,pred))
print()
print('Confusion Matrix:\n', confusion_matrix(y_test,pred))
print()
print('Accuracy : ', accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix:
 [[862   8]
 [  1 268]]

Accuracy :  0.9920983318700615
